language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
jobs:
  include:
    - stage: lint
      python: 3.8
      script:
        # run flake8 style tests - ignore code complexity checks
        - flake8 hjson setup.py --extend-ignore=C901,R701,CCR001
        # run isort import checks
        - isort -c -rc hjson setup.py
        # run black formatting check
        - black --quiet --check hjson setup.py

script:
  # run test suite
  - coverage run --source=hjson -m pytest hjson/tests
  # get coverage
  - coverage report -m

