language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"

install:
  # install hjson
  - pip install .
  # install testing infrastructure
  - pip install pytest coverage codecov flake8 isort
  # install black if Python3
  - pip install black

script:
  - echo "$TRAVIS_PYTHON_VERSION"

  - flake8 hjson
  - coverage run -m pytest
  - isort -c -rc hjson tests setup.py

  - black --check hjson tests setup.py

after_success:
  - codecov
