language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
jobs:
  include:
    - stage: lint
      python: 3.8
      script: ./.travis/lint.sh
script: ./.travis/test.sh
