language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

install:
  # install hjson
  - pip install .
  # install testing infrastructure
  - pip install pytest coverage codecov flake8 isort
  # install isort black if Python3
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then pip install isort black; fi

script:
  - echo "$TRAVIS_PYTHON_VERSION"

  - flake8 hjson
  - coverage run -m pytest

  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then isort -c -rc hjson tests setup.py; black --check hjson tests setup.py; fi

after_success:
  - codecov
