language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  # install hjson
  - pip install .

  # install testing infrastructure
  - pip install pytest coverage codecov flake8 isort black

  # see what's installed
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"

  # tests
  - flake8 hjson
  - coverage run -m pytest
  - isort -c -rc hjson tests setup.py
  - black --check hjson tests setup.py

after_success:
  - codecov
